from .extraction import (
    SYSTEM_PROMPT_EXTRACTOR,
    EXTRACTION_USER_PROMPT,
    EXTRACTION_FOLLOW_UP,
)
from .hypothesis import (
    SYSTEM_PROMPT_HYPOTHESIS,
    HYPOTHESIS_TEST_PROMPT,
    HYPOTHESIS_CHALLENGE_PROMPT,
)
from .synthesis import (
    SYSTEM_PROMPT_SYNTHESIS,
    PATTERN_SYNTHESIS_PROMPT,
    CLUSTER_EVIDENCE_PROMPT,
    CONFIDENCE_ASSESSMENT_PROMPT,
)
from .stakeholder import (
    SYSTEM_PROMPT_STAKEHOLDER,
    STAKEHOLDER_SUMMARY_PROMPT,
    CONVINCE_STAKEHOLDER_PROMPT,
    RESEARCH_GAPS_PROMPT,
    COUNTER_EVIDENCE_PROMPT,
)
